### ISSUE TITLE
Peer to Peer code Review

### ISSUE THREAD

**Issue by misalazeem** [misalazeem/My-Portfolio----Microverse-Project#9]
Desktop version code review: 
Give me a comment below.

**Comment by ragangithub** [comment]
your project looks great. It would be better if you use a section to divide parts of the page

**Comment by Abdulwhbhussain** [comment]
The UI of Your Project Matches Exactly the Figma Design; I appreciate your efforts and attention to details.

**Comment by clin2on3mun** [comment]
Hey @misalazeem 
Good job your project looks fantastic :thumbsup: I would suggest you use alt:pinched_fingers: as another attribute in your **Img tag** it is really helpful when images can't be displayed on the webpage alt informs the user that there is an image. but everything is great

**Comment by Abdulwhbhussain** [comment]
1- wrap your navigation link for desktop in html in <ul></ul> and <li></li>
